repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
      args: [
        "-l 92",
        "-t py38"
      ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: requirements-txt-fixer
    - id: mixed-line-ending
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    - id: pylint
      args: [
        "--disable=import-error,too-many-locals,too-many-locals,too-many-branches,too-many-statements",
        "--disable=too-many-arguments,too-many-instance-attributes"
      ]
      exclude: (?x)^(test_(.+)|time_(.+))$